### ISSUE TITLE
JWT

### ISSUE THREAD

**Issue by dev4jam** [skelpo/UserManager#12]
Could you please explain how to generate this N and D values from JWT? I used JWT with NodeJS but never faced with a manual configuration of those parameters.

**Comment by dev4jam** [comment]
PEM

**Comment by calebkleveter** [comment]
@dev4jam 

First, I want to note that because certificates only contain public keys, you can only read and verify signed JWTs with them, not sign them.

But for using a PEM cert, I just made an update to one of the dependencies for this project (JWTVapor), so if you update your packages (`swift package update` or `vapor update -y`) the should be a class `CertService` exported from it. If you go into your global `configure` function, you can change the `JWTProvider` closure to something like this:

```swift
let jwtProvider = JWTProvider { cert in
    let headers = JWTHeader(alg: "RS256", crit: ["exp", "aud"], kid: "user_manager_kid")
    return try CertService(certificate: cert, header: headers)
}
```

The `JWT_SECRET` environment variable should then be set to the PEM certificate you are using. Another option would be to create an empty environment variable (the provider expects one and will throw an error if one doesn't exist) and then read the cert from disk using `FileManager`.

**Comment by proggeramlug** [comment]
Can you do me a favor? Try this little bash-script with your key-file and see if that works:
```bash
#!/bin/bash

data=$(openssl rsa -in my-key.key -noout -modulus)
length=${#data}
modulus=${data:8:length}
modulusMd5="test"
echo "N:"
echo $modulus | xxd -r -p | base64
data=$(openssl rsa -in dummy.key -noout -text)
p1=$(echo $data | python -c 'print(raw_input().index("privateExponent: "))+17')
p2=$(echo $data | python -c 'print(raw_input().index("prime1:"))')
d=$((p2-p1))
p=$(echo $data)
echo "D:"
echo ${p:p1:d} | xxd -r -p | base64
```

make sure to adjust "my-key.key" to match your file

**Comment by dev4jam** [comment]
It printed out:

N:
6vIAUNUo3xGPvlzP+1KxxWQ8rSmJiqAuyDJJbYqlOeqOjIVQNAC8CdKv2hisGnUTxFw+tY0Dm0girCSgePC4ma2t7USzqcoStgNUAvPXBtEY1jiPl83XByZP8qE4FSEcFvP9rLyHWiw+haRKijQl0JJnrnjaU0G4BNepWUVyNPcSVrPKo5PT297OGOjMaolIEUTF0I2pPelY1hCGus7t2stm4Qa2swAZAj6kq6QPgJzrtTYKPSfAUDSP0HCHedBXZBfxDQ7OGuxjv0WRN2O/5wJnBzGayu2DdB2JPotcMzVSi1ThyKx1ACYkbLF2ViWFSkwZNeEZzCiNsmg83narkw==
D:
NAGrtjjpGi+9/Op4k25jsYkVsVMPgiMhF+mhvWDCYEaelVZxQYGkHhyIFqP9fMHLxVyR+Qgk8zuNiUN2Ti8i/cmnRW0+w+faKnYkI58sSvMAJ3NPvc+vuIJvkgrD6lFw8VfDIHh/EaPXlyed5GfUsw2la8aOtX1HqbK/ZuZreHOIBMqP94chN9sA6Gyuv663mzhKoWJlCQGito7cCNtwYuR/mdLV2vLQsX+PENM5qO8InCJCflEjuZgP37jeb1jTiWYdPNW+3oMwo/Us5Tjn3DrYye5jefKiF+wbzapSs2nlnCL+mrA6VG1ZZ0CZ3b+V+8s++vvo3pYqDosFyb4XMQ==

**Comment by dev4jam** [comment]
is that exactly what I need to set in the configuration?

**Comment by proggeramlug** [comment]
Those should be the values you need, yes.

Note: Since they are now public in GitHub I hope this is not some kind of production environment. :)

**Comment by dev4jam** [comment]
sure 😂
